### ISSUE TITLE
大佬，有yaml文件配置吗

### ISSUE THREAD

**Issue by lxz946786639** [JackHuang021/ld2410s#1]
大佬，请问有yaml文件配置吗

**Comment by JackHuang021** [comment]
暂时还没什么时间弄，还只弄了基本功能，可以给你参考一下哈
```yaml
esphome:
  name: esphome-web-73ec28
  friendly_name: ESPHome Web 73ec28

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  # add ld2410s repo
  source:
    type: local
    path: ld2410s/components/
  # refresh: 0s

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "Your key"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-73Ec28"
    password: "yd36bGe7X5UY"

# uart set
uart:
  id: ld2410s_uart
  tx_pin: 17
  rx_pin: 16
  baud_rate: 115200
  parity: none
  stop_bits: 1

ld2410s:
  uart_id: ld2410s_uart

binary_sensor:
  - platform: ld2410s
    has_target:
      name: Presence

  # ld2410s out
  - platform: gpio
    pin: 2
    name: "Presence Out"
    device_class: presence

number:
  - platform: ld2410s
    timeout:
      name: timeout
    max_distance:
      name: max detected distacne
    min_distance:
      name: min detected distance
    status_report_freq:
      name: status report frequency
    distance_report_freq:
      name: distance report frequency      
    g0:
      trigger_threshold:
        name: g0 tigger threshold
      keep_threshold:
        name: g0 keep threshold
    g1:
      trigger_threshold:
        name: g1 tigger threshold
      keep_threshold:
        name: g1 keep threshold
    g2:
      trigger_threshold:
        name: g2 tigger threshold
      keep_threshold:
        name: g2 keep threshold
    g3:
      trigger_threshold:
        name: g3 tigger threshold
      keep_threshold:
        name: g3 keep threshold
    g4:
      trigger_threshold:
        name: g4 tigger threshold
      keep_threshold:
        name: g4 keep threshold
    g5:
      trigger_threshold:
        name: g5 tigger threshold
      keep_threshold:
        name: g5 keep threshold
    g6:
      trigger_threshold:
        name: g6 tigger threshold
      keep_threshold:
        name: g6 keep threshold
    g7:
      trigger_threshold:
        name: g7 tigger threshold
      keep_threshold:
        name: g7 keep threshold
    g8:
      trigger_threshold:
        name: g8 tigger threshold
      keep_threshold:
        name: g8 keep threshold
    g9:
      trigger_threshold:
        name: g9 tigger threshold
      keep_threshold:
        name: g9 keep threshold
    g10:
      trigger_threshold:
        name: g10 tigger threshold
      keep_threshold:
        name: g10 keep threshold
    g11:
      trigger_threshold:
        name: g11 tigger threshold
      keep_threshold:
        name: g11 keep threshold
    g12:
      trigger_threshold:
        name: g12 tigger threshold
      keep_threshold:
        name: g12 keep threshold
    g13:
      trigger_threshold:
        name: g13 tigger threshold
      keep_threshold:
        name: g13 keep threshold
    g14:
      trigger_threshold:
        name: g14 tigger threshold
      keep_threshold:
        name: g14 keep threshold
    g15:
      trigger_threshold:
        name: g15 tigger threshold
      keep_threshold:
        name: g15 keep threshold
```
